version: '3.9'

services:
  wiremock:
    image: brainiac/multiarch-wiremock:0.1.0
    container_name: wiremock
    volumes:
      - ./__files:/home/wiremock/__files
      - $PWD/mappings:/home/wiremock/mappings
    ports:
      - "8080:8080"
    command:
      - --verbose
      - --global-response-templating